# Zona14: translated Russian names/descriptions to English
- type: entity
  parent: STBaseStructure
  id: STBaseTrashCache
  abstract: true
  name: garbage
  description: A pile of junk, it may be worth looking for something usable in it.
  components:
    - type: TimedDespawn
      lifetime: 1800
    - type: Transform
      noRot: true
    - type: Storage
      maxItemSize: Ginormous
      grid:
        - 0,0,9,9
    - type: ContainerContainer
      containers:
        storagebase: !type:Container
    - type: UserInterface
      interfaces:
        enum.StorageUiKey.Key:
          type: StorageBoundUserInterface
