# Zona14: translated Russian names/descriptions to English
- type: entity
  id: StalkerRail
  name: rails
  description: Old railway tracks, the sleepers of which are already rotten, and the metal is rusted.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Appearance
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/rails.rsi
    drawdepth: FloorTiles
    layers:
      - state: rail
        scale: 0.6, 0.6
  - type: Transform
    anchored: true
  # - type: Physics
    # bodyType: Static
  - type: FootstepModifier
    footstepSoundCollection:
      collection: FootstepCatwalk
      params:
        volume: 8

# Zona14: TANKER WAGONS

- type: entity
  id: StalkerCargoTank
  parent: BaseStructure
  name: Wagon with tank
  description: A type of railway rolling stock for the transportation of liquids, including oil and its refined products, chemically active and corrosive liquid substances.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoTank1
  parent: BaseStructure
  name: "{ ent-StalkerCargoTank }"
  description: "{ ent-StalkerCargoTank.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_tank1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# Zona14: DIESEL LOCOMOTIVES

- type: entity
  id: StalkerPassHead
  parent: BaseStructure
  name: Diesel locomotive M62
  description: Soviet mainline six-axle diesel locomotive, originally developed for operation in the CMEA countries. It has been produced by the Lugansk Diesel Locomotive Plant since 1965.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_head
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead
  parent: BaseStructure
  name: Diesel locomotive TEM6-001
  description: Soviet six-axle shunting diesel locomotive, manufactured by the Bryansk plant. It was created as a universal locomotive, which, after replacing bogies or wheelsets, could operate on railways with a gauge of 1000, 1067, 1435 and 1520 mm, and in both temperate and tropical climates.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: head_cargo
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead1
  parent: BaseStructure
  name: "{ ent-StalkerPassHead }"
  description: "{ ent-StalkerPassHead.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_head # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargoHead2
  parent: BaseStructure
  name: "{ ent-StalkerCargoHead }"
  description: "{ ent-StalkerCargoHead.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo_head2 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# Zona14: PASSENGER WAGONS

- type: entity
  id: StalkerPassTrain
  parent: BaseStructure
  name: passenger car
  description: A unit of rolling stock intended for the carriage of passengers.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain1
  parent: BaseStructure
  name: "{ ent-StalkerPassTrain }"
  description: "{ ent-StalkerPassTrain.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train1
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerPassTrain2
  parent: BaseStructure
  name: "{ ent-StalkerPassTrain }"
  description: "{ ent-StalkerPassTrain.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: passenger_train3
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

# Zona14: FREIGHT WAGONS

- type: entity
  id: StalkerCargo
  parent: BaseStructure
  name: freight wagon
  description: Is a non-powered railway vehicle that was used to transport goods.
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo1
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo1 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo2
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo2 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo3
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo3 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo4
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo4 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo5
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo5 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo6
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo6 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

- type: entity
  id: StalkerCargo7
  parent: BaseStructure
  name: "{ ent-StalkerCargo }"
  description: "{ ent-StalkerCargo.desc }"
  suffix: ST, Mapping
  placement:
    mode: AlignTileAny
  components:
  - type: Sprite
    sprite: _Stalker/Structures/Railroad/Train.rsi
    layers:
      - state: cargo7 # Zona14: fixed Cyrillic с→c
  - type: Transform
    anchored: true
  - type: Physics
    bodyType: Static
  - type: Fixtures
    fixtures:
      fix1:
        shape:
          !type:PhysShapeAabb
          bounds: "-1.5,-1.0,1.5,1.0"
        density: 5000
        mask:
        - LargeMobMask
        layer:
        - WallLayer
  - type: Appearance

