using Content.Shared.Administration.BanList;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using static Robust.Client.UserInterface.Controls.BaseButton;

namespace Content.Client.Administration.UI.BanList.RoleBans;

[GenerateTypedNameReferences]
public sealed partial class RoleBanListLine : BoxContainer, IBanListLine<SharedServerRoleBan>
{
    public SharedServerRoleBan Ban { get; }

    public event Action<RoleBanListLine>? IdsClicked;
    public event Action<RoleBanListLine>? PardonClicked; // Zona14

    private Button? _pardonButton; // Zona14

    public RoleBanListLine(SharedServerRoleBan ban)
    {
        RobustXamlLoader.Load(this);

        Ban = ban;
        IdsHidden.OnPressed += IdsPressed;

        BanListEui.SetData(this, ban);
        Role.Text = ban.Role;

        // Zona14: add pardon button to active role bans
        if (ban.Id is not null && ban.Unban is null)
        {
            _pardonButton = new Button
            {
                Text = Loc.GetString("ban-list-pardon"),
            };
            _pardonButton.OnPressed += PardonPressed;
            AddChild(_pardonButton);
        }
        // End Zona14
    }

    private void IdsPressed(ButtonEventArgs buttonEventArgs)
    {
        IdsClicked?.Invoke(this);
    }

    // Zona14
    private void PardonPressed(ButtonEventArgs buttonEventArgs)
    {
        PardonClicked?.Invoke(this);
    }
    // End Zona14

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);

        IdsHidden.OnPressed -= IdsPressed;
        IdsClicked = null;

        // Zona14
        if (_pardonButton != null)
            _pardonButton.OnPressed -= PardonPressed;
        PardonClicked = null;
        // End Zona14
    }
}
