// SPDX-FileCopyrightText: 2026 taydeo <tay@funkystation.org>
//
// SPDX-License-Identifier: MIT
// Ported from funky-station Content.Client/_Funkystation/ContentWarning/ContentWarningPopup.xaml.cs@2e50750ab6

using Content.Client.UserInterface.Controls;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Utility;

namespace Content.Client._Zona14.ContentWarning;

[GenerateTypedNameReferences]
public sealed partial class ContentWarningPopup : FancyWindow
{
    public event Action? OnContentWarningAccept;
    public event Action? OnContentWarningReject;

    public ContentWarningPopup()
    {
        RobustXamlLoader.Load(this);

        InitWindow();
    }

    private void InitWindow()
    {
        ContentWarningBody.SetMessage(FormattedMessage.FromMarkupOrThrow(Loc.GetString("content-warning-message")));

        ContentWarningReject.OnPressed += _ =>
        {
            OnContentWarningReject?.Invoke();
        };

        ContentWarningAccept.OnPressed += _ =>
        {
            OnContentWarningAccept?.Invoke();
        };
    }
}
