- type: job
  id: StalkerGuide
  name: job-guide
  icon: guide
  description: job-stalker-desc
  playTimeTracker: JobGuide
  whitelisted: true
  requirements:
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
      - Gingerbread
      - HumanFat
    # Zona14: Reset requirements since people cannot join as stalker when kicked
    # Zona14: from GP. And essentially can't play at all. I don't know how to make it better, but what we have now
    # Zona14: doesn't let people play at all.
    # - !type:DepartmentTimeRequirement
    #   department: StalkerAdvanced
    #   time: 1
    #   inverted: true
    # - !type:DepartmentTimeRequirement
    #   department: StalkerBrigands
    #   time: 1
    #   inverted: true
    # - !type:DepartmentTimeRequirement
    #   department: StalkerOfficials
    #   time: 1
    #   inverted: true
    # - !type:DepartmentTimeRequirement
    #   department: StalkerReligius
    #   time: 1
    #   inverted: true
    # - !type:DepartmentTimeRequirement
    #   department: StalkerAnomalists
    #   time: 1
    #   inverted: true
  startingGear: StalkerGear
  supervisors: job-stalker-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        tags:
          - Stalker
          - Guide
      - type: Bands
        band: Stalker
        bandIcon: guide
        bandProto: STStalkerBand
        bandRankId: 2
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3
      - type: STAnomalyTipsViewing
