// SPDX-License-Identifier: MIT

using System.Linq;
using System.Text;
using Content.Client.Administration.UI.CustomControls;
using Content.Client._Zona14.UserInterface.Systems.MentorHelp;
using Content.Shared.Administration;
using Content.Shared._Zona14.Administration.MentorHelp;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Network;
using Robust.Shared.Utility;

namespace Content.Client._Zona14.Administration.UI.MentorHelp;

[GenerateTypedNameReferences]
public sealed partial class MentorHelpControl : Control
{
    [Dependency] private readonly IUserInterfaceManager _ui = default!;

    private readonly IMentorHelpController _controller;
    private readonly Dictionary<NetUserId, MentorHelpPanel> _activePanelMap = new();
    private PlayerInfo? _currentPlayer;

    public MentorHelpControl(IMentorHelpController controller)
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);

        _controller = controller;
        _controller.MentorHelpReceived += OnMentorHelpReceived;
        _controller.MentorHelpTypingUpdated += OnMentorHelpTypingUpdated;

        OnVisibilityChanged += _ =>
        {
            foreach (var panel in _activePanelMap.Values)
            {
                if (panel.Visible)
                    panel.Unread = 0;
            }
        };

        ChannelSelector.OnSelectionChanged += sel =>
        {
            _currentPlayer = sel;
            SwitchToChannel(sel?.SessionId);
            ChannelSelector.PlayerListContainer.DirtyList();
        };

        ChannelSelector.OverrideText += (info, text) =>
        {
            var sb = new StringBuilder();

            if (info.Connected)
                sb.Append(info.ActiveThisRound ? '⚫' : '◐');
            else
                sb.Append(info.ActiveThisRound ? '⭘' : '·');

            sb.Append(' ');
            if (_activePanelMap.TryGetValue(info.SessionId, out var panel) && panel.Unread > 0)
            {
                if (panel.Unread < 11)
                    sb.Append(new Rune('➀' + (panel.Unread - 1)));
                else
                    sb.Append(new Rune(0x2639)); // ☹
                sb.Append(' ');
            }

            sb.AppendFormat("\"{0}\"", text);
            return sb.ToString();
        };

        ChannelSelector.Comparison = (a, b) =>
        {
            _activePanelMap.TryGetValue(a.SessionId, out var aPanel);
            _activePanelMap.TryGetValue(b.SessionId, out var bPanel);

            if (a.IsPinned != b.IsPinned)
                return a.IsPinned ? -1 : 1;

            var aUnread = aPanel?.Unread > 0;
            var bUnread = bPanel?.Unread > 0;
            if (aUnread != bUnread)
                return aUnread ? -1 : 1;

            var aRecent = a.ActiveThisRound && aPanel?.LastMessage != DateTime.MinValue;
            var bRecent = b.ActiveThisRound && bPanel?.LastMessage != DateTime.MinValue;
            if (aRecent != bRecent)
                return aRecent ? -1 : 1;

            if (a.Connected != b.Connected)
                return a.Connected ? -1 : 1;

            if (!a.Connected && !b.Connected && a.ActiveThisRound != b.ActiveThisRound)
                return a.ActiveThisRound ? -1 : 1;

            return (bPanel?.LastMessage ?? DateTime.MinValue).CompareTo(aPanel?.LastMessage ?? DateTime.MinValue);
        };
    }

    public void OnMentorHelpReceived(MentorHelpTextMessage message)
    {
        ChannelSelector.PopulateList();

        var panel = EnsurePanel(message.UserId);
        panel.ReceiveLine(message);

        if (_currentPlayer?.SessionId == message.UserId)
        {
            SwitchToChannel(message.UserId);
            ChannelSelector.PlayerListContainer.DirtyList();
        }
    }

    public void OnMentorHelpTypingUpdated(MentorHelpPlayerTypingUpdated message)
    {
        if (_activePanelMap.TryGetValue(message.Channel, out var panel))
            panel.UpdatePlayerTyping(message.PlayerName, message.Typing);
    }

    public void SelectChannel(NetUserId channel)
    {
        if (!ChannelSelector.PlayerInfo.TryFirstOrDefault(i => i.SessionId == channel, out var info))
            return;

        var data = new PlayerListData(info);
        if (!ChannelSelector.PlayerListContainer.Data.Contains(data))
            ChannelSelector.StopFiltering();

        ChannelSelector.PopulateList();
        ChannelSelector.PlayerListContainer.Select(data);
    }

    public void PopulateList()
    {
        var pinnedPlayers = ChannelSelector.PlayerInfo.Where(p => p.IsPinned).ToDictionary(p => p.SessionId);

        ChannelSelector.PopulateList();

        foreach (var player in ChannelSelector.PlayerInfo)
        {
            if (pinnedPlayers.TryGetValue(player.SessionId, out var pinnedPlayer))
                player.IsPinned = pinnedPlayer.IsPinned;
        }
    }

    private MentorHelpPanel EnsurePanel(NetUserId channelId)
    {
        if (_activePanelMap.TryGetValue(channelId, out var existingPanel))
            return existingPanel;

        var panel = new MentorHelpPanel(text => _controller.SendMessage(channelId, text, PlaySound.Pressed));
        panel.InputTextChanged += text => _controller.SendInputTextUpdated(channelId, !string.IsNullOrEmpty(text));
        panel.Visible = false;
        MentorHelpArea.AddChild(panel);
        _activePanelMap[channelId] = panel;

        return panel;
    }

    private void SwitchToChannel(NetUserId? channel)
    {
        HideAllPanels();

        if (channel != null)
        {
            var panel = EnsurePanel(channel.Value);
            panel.Visible = true;
        }
    }

    private void HideAllPanels()
    {
        foreach (var panel in _activePanelMap.Values)
        {
            panel.Visible = false;
        }
    }

    protected override void Dispose(bool disposing)
    {
        base.Dispose(disposing);
        _controller.MentorHelpReceived -= OnMentorHelpReceived;
        _controller.MentorHelpTypingUpdated -= OnMentorHelpTypingUpdated;
    }
}
