- type: shopPreset
  id: Z14ProjectShopPreset # 0.7x
  itemsForSale:
# MARK: Artifacts
    # Thermal group - 1
    Z14ZoneArtifactFireball: 720
    Z14ZoneArtifactEye: 960
    Z14ZoneArtifactFlame: 1440
    # Thermal group - 2
    Z14ZoneArtifactCristall: 2880
    Z14ZoneArtifactLithosphere: 5760
    # Electrical group - 1
    Z14ZoneArtifactSparkler: 660
    Z14ZoneArtifactBattery: 840
    Z14ZoneArtifactFlash: 1440
    Z14ArtMoon: 2880
    Z14ZoneArtifactTesla: 4320
    Z14ZoneArtifactIce: 5760
    # Gravity group - 1
    Z14ArtMedusa: 660
    Z14ZoneArtifactFlower: 900
    Z14ZoneArtifactNightStar: 2880
    # Gravity group - 2
    Z14ZoneArtifactVyvert: 780
    Z14ZoneArtifactAmoeba: 1020
    Z14ZoneArtifactFloodlight: 972
    Z14ZoneArtifactGravi: 1440
    Z14ZoneArtifactGoldfish: 5760
    Z14ZoneArtifactSpring: 4320
    Z14ZoneArtifactFocus: 4320
    Z14ZoneArtifactStuntman: 5760
    Z14ZoneArtifactDistorter: 5760
    Z14ZoneArtifactSoul: 4320
    # Food
    Z14FoodMeatDogCooked: 84
    Z14STFoodMeatSpiderCooked: 42
    Z14FoodMeatBoarCooked: 132

    # Acidic group - 1
    Z14ZoneArtifactBlood: 1440
    Z14ZoneArtifactMeat: 2880
    Z14ZoneArtifactKolobok: 4320
    # Acidic group - 2
    Z14ZoneArtifactPellicle: 660
    Z14ZoneArtifactBaloon: 4320

    # New

    Z14ZoneArtifactAccumulator: 840
    Z14ZoneArtifactDiamond: 2880
    Z14ZoneArtifactCharger: 2880
    Z14ZoneArtifactToxic: 840
    Z14ZoneArtifactCytoplasm: 720
    Z14ZoneArtifactCompass: 2880
    Z14ZoneArtifactCrucifix: 5760
    Z14ZoneArtifactThorn: 1140
    Z14ZoneArtifactArf: 840
    Z14ZoneArtifactDarkCube: 5760
    Z14ZoneArtifactBunch: 1140
    Z14ZoneArtifactRock: 1140
    Z14ZoneArtifactSun: 2880
    Z14ZoneArtifactRoot: 2880
    Z14ZoneArtifactConflagration: 1140
# MARK: Mutant Parts
    # Mutant parts

    #Boars -------- Health * T * 0.45
    Z14MutantPartBoarHoof: 264 # T1
    Z14MutantPartSeasonedBoarHoof: 528 # T2
    Z14MutantPartOldBoarHoof: 780 # T3

    #T1 -------- Health * 1
    Z14MutantPartBlindDogTail: 108
    Z14MutantPartFleshEye: 198
    FoodMeatSpiderLeg: 72

    #T2 -------- Health * 1.8
    Z14MutantPartLeshiyRoot: 840
    Z14MutantPartPseudodogTail: 360
    Z14MutantPartSnorkFoot: 540

    #T3 -------- Health * 3
    Z14MutantPartPsiDogTail: 564
    Z14MutantPartBloodsuckerTentacles: 1200
    Z14MutantPartOraculeEye: 1560
    Z14MutantPartPseudogiantHeart: 9360
    Z14MutantPartZombieHand: 660

    # Mutant parts EN

    Z14MutantPartCatGland: 100
    Z14MutantPartBearClaw: 300
    Z14MutantPartBearPaw: 576
    Z14MutantPartBearEye: 1140
    Z14MutantPartFrogLeg: 480
    Z14MutantPartIzlomArm: 2520
    Z14MutantPartChimeraTooth: 3600

# MARK: Values & Meat
    # Values
    Dollar: 60
    Goldcoins: 5670

    # meat
    Z14FoodMeatSTRatJerked: 10
    Z14FoodMeatSTDogJerkedSingle: 75
    Z14FoodMeatSTBoarJerkedSingle: 125
    Z14FoodMeatSTBearJerkedSingle: 245
    Z14FoodMeatSTSuckerJerkedSingle: 600
    Z14STFoodJarCherriesPickled: 1350
    Z14STFoodJarJamBerry: 1350
    Z14STFoodJarKvass: 2300
    Z14STFoodJarSalo: 350
    Z14STFoodJarEggs: 375
    Z14STFoodJarMeatSausage: 775
    Z14STFoodJarMeatFishFillet: 300
    Z14STFoodJarMeatFishSteak: 850
    Z14STFoodJarMeatEel: 1250
    Z14STFoodJarWholeEelFermented: 2100

# MARK: Items to Buy
  categories:
  - name: shop-category-weapons
    priority: 1
    items:
      Z14STWeaponSMGPP19: 2000
      Z14STWeaponRifleAKS74: 3500
      Z14STWeaponRifleSCARH: 6500
      Z14STWeaponRifleG36: 6000
      STWeaponShotgunProtecta: 3000
      Z14STWeaponSniperVepr: 6000
  - name: shop-category-magazines
    priority: 2
    items:
      545Mag30: 400
      BizonMag: 300
      754Mag10: 700
      STSpeedLoader45ACPEmpty: 500
      751Mag30: 600
  - name: shop-category-ammunition
    priority: 3
    items:
      6mmBuckshotBox: 100
      8mmBuckshotBox: 350
      Z1445ACPRIPBox: 300
      Z1445ACPMFMJBox: 150
      Z1445ACPAPBox: 600
      Z14556WarmagBox: 250
      Z14556M855Box: 1300
      Z14754FMJBox: 1500
      Z14545HPBox: 150
      Z14545PCBox: 1250
      Z14545BPBox: 1900
      Z14918PBMBox: 600
      Z14751UNBox: 800
      Z14751M80Box: 1600
  - name: shop-category-armor
    priority: 4
    items:
      Z14STClothingOuterArmorProjectZarya: 1200
      Z14ClothingOuterArmorSevaProjectGROM9: 4500
      Z14STClothingOuterArmorLightPlateVestBaseProject: 1000
      Z14STClothingOuterArmorLightPlateVestBaseANAproject: 1500
      Z14ClothingHeadHelmetInfantryProject: 300
      Z14ClothingHeadHelmetLightProject: 150
      Z14ClothingHeadHelmetBerill5MProject: 3250
      Z14ClothingOuterArmorBerill5MProject: 10000
  - name: shop-category-storage-and-containers
    priority: 5
    items:
      MedkitGrizzlyStalker: 2000
      Z14ClothingBackpackDuffelMilitaryOlive: 700
  - name: shop-category-raincoats-and-gasmasks
    priority: 6
    items:
      Z14ClothingMaskGasXM40Project: 500
      Z14ClothingOuterCoatLoyalist: 2000
      Z14STClothingCapeArmorChainmailSeva: 2000
  - name: shop-category-research-equipment
    priority: 7
    items:
      STBoltBagFilled: 50
      Z14BoxArtcont: 500
      Z14ZoneAnomalyDetectorUpgradeAD2: 2000
      Z14ZoneArtifactDetectorSpruce: 3400
  - name: shop-category-utilities
    priority: 8
    items:
      STElasticRubberRed: 15
      STElasticRubberGreen: 15
      STElasticRubberBlue: 15
      STRadioHeadset: 150
      ToolkitTearOne: 35000
      CraftSaw: 20000
      Z14STCombatKnife: 25
      BoxZiptie: 50
      BoxSafebox: 300
      CheapLighter: 5
      GeigerCounter: 50
      Z14BaseRadio: 50
      STFlashlightSeclite: 50
      PowerCellHyper: 50
      HandheldGPSBasic: 50
      Paper: 2
      Pen: 5
      longrangemetaldetector: 1500
      AAAAStalkerLopata: 200
      Z14Binocularus1: 2500
      BoxFlare: 60
      Beaker: 40
      Syringe: 20
      Z14ClothingGoPro: 250
      ExtendedEmergencyOxygenTankFilledStalker: 50
      Matchbox: 10
      HatchetStalker: 150
      KordonMapStack: 1200
  - name: shop-category-provisions
    priority: 9
    items:
      Z14STEnergyDrink: 100
      Z14STEnergyDrinkMonster: 200
      Z14STEnergyDrinkRevo: 50
      Z14STDrinkBeerCanBaltic: 40
      DrinkVodkaBottleFull: 100
      Z14STFoodBreadPlain: 60
      DrinkFlaskOld: 60
      DrinkWaterBottleFull: 100
      FoodTinMRE: 500
      Z14DrinkLemonadehBottleFull: 100
      Z14STFoodMeatSalami: 1000
  - name: shop-category-medicine
    priority: 10
    items:
      Z14STPillboxAntirad: 350
      Z14STGauze: 65
      Z14STOintment: 75
      Z14STBrutepack: 65
      Bloodpack: 450
      Z14MedkitAI2: 100
      Defibrillator: 1000
      Z14AntiRadMedipen: 300
      Z14STPillboxProbud: 500
      Z14MedkitMilitary: 250
      Z14MedkitScience: 300
      Z14MedkitElite: 1200
      Z14MedkitLAR: 2800
      Z14STPillboxShiza: 10000
  - name: shop-category-modules
    priority: 11
    items:
      STModuleScopeRiflesT1Ru: 1600
      STModuleScopeRiflesT1Nato: 1600
      STModuleSilencerRiflesT1Ru: 1400
      STModuleSilencerRiflesT1Nato: 1400
      STModuleShotgunChokeT1: 1200
      STModuleSMGGripT1: 1600
      STModuleSilencerSMGT1: 1600
      STModuleSniperSightT1: 1600
      STModuleSilencerSniperT1: 1400
  - name: shop-category-customization
    priority: 12
    items:
      Z14ClothingBandageStalkerJid: 50
      Z14ClothingBandageStalkerBelarus: 50
      Z14ClothingHeadHatBeaniehat: 10
      Z14ClothingMaskNeckFacemask: 10
      Z14ClothingMaskNeckBalaklava1: 10
      Z14ClothingMaskNeckBalaklava2: 10
      Z14ClothingMaskNeckBalaklava3: 10
      ClothingHeadBandMerc: 30
      ClothingHeadBandSkull: 30
      ClothingHeadHatUshanka: 30
      ClothingHandsGlovesFingerless: 30
      ClothingHandsGlovesMercFingerless: 60
      ClothingShoesColorBlack: 30
      ClothingShoesBootsWork: 30
      ClothingShoesLeather: 30
      ClothingShoesBootsMerc: 30
      ClothingShoesSwat: 35
      ClothingHeadHatBlacksoft: 10
      ClothingHeadHatGreysoft: 10
      Z14ClothingHeadHatSovietUshankaStalker: 40
      Z14ClothingCloakStalker: 30
      Z14ClothingLegsJeansBlue: 10
      Z14ClothingLegsJeansStalker: 10
      Z14ClothingLegsJeansGreenCargo: 10
      Z14ClothingLegsJeansGreyCargo: 10
      Z14ClothingLegsJeansBlackCargo: 10
      Z14ClothingLegsJeansBrownCargo: 10
      Z14ClothingLegsJeansSandCargo: 10
      Z14ClothingLegsJeansRussianPixel: 20
      Z14ClothingLegsJeansBlackNew: 20
      Z14ClothingLegsJeansGorka: 20
      ClothingShoesBootsCombat: 30
      Z14ClothingTorsoTShirtPivozavr: 30
      Z14ClothingTorsoTShirtSailorSuit: 30
      Z14ClothingTorsoTShirtColorBlack: 30
      Z14ClothingTorsoTurtlenecksBlack: 90
      Z14ClothingTorsoTurtlenecksGorka: 90
      Z14ClothingTorsoTurtlenecksGorka6: 90
      Z14ClothingTorsoTurtlenecksBereza: 90
      Z14ClothingLegsJeansBereza: 20
      Z14ClothingLegsJeansGorka6: 20
      Z14ClothingTorsoTurtlenecksGorkaRus: 90
      Z14ClothingOuterCoatKKK: 67
      # new shit
      Z14ClothingLegsBattlePantsBlack: 50
      Z14ClothingLegsVeryBlueJenas: 50
      Z14ClothingLegsCombatForest: 50
      Z14ClothingLegsGorka5: 50
      Z14ClothingLegsGorka6b: 50
      Z14ClothingLegsNavyPants: 50
      Z14ClothingLegsRussianNumber: 50
      Z14ClothingTorsoTurtlenecksBattleTurtleneckbBlack: 50
      Z14ClothingTorsoTurtlenecksBlackTurtleneck: 50
      Z14ClothingTorsoTurtlenecksCombatForest: 50
      Z14ClothingTorsoTurtlenecksGorka5: 50
      Z14ClothingTorsoTurtlenecksGorka6B: 50
      Z14ClothingTorsoTurtlenecksKhakiTurtleneck: 50
      Z14ClothingTorsoTurtlenecksMatrosska: 50

  sponsorCategories:
    SponsorBread:
    - name: sponsor
      items:
        Z14STWeaponRifleAKMC: 4300
        Z14STWeaponRifleAKS74UWhite: 1350
        STHatchetSponsor: 150
        STSpanishKnife: 100
    SponsorOMind:
    - name: O-Consciousness
      items:
        Z14STWeaponRifleSVDSWood: 800
        Base754Mag5: 400
  contributorCategories:
  - name: contributor
    items:
      STWeaponShotgunMP153Raven: 550
      Z14WeaponPistolStalkerAPSHugo: 450


